postgresql: &postgresql
  adapter: postgresql
  host: localhost
  min_messages: ERROR
  username: mikesaurio
  password: maikisaurio
  pool: 5
  timeout: 5000

development:
  <<: *postgresql
  database: imagenes_random_development

test:
  <<: *postgresql
  database: imagenes_random_test

production:
  <<: *postgresql
  database: imagenes_random_production
